site_name: solar
site_description: App operacional da PMSE
repo_url: https://github.com/isisaraujo/solar-api
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/isisaraujo">isisaraujo</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
