# Generated by Django 5.1.7 on 2025-08-12 12:00

import django.core.validators
import django.db.models.deletion
import solar.documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_code', models.CharField(max_length=50, unique=True, verbose_name='Código único do cliente')),
                ('project_holder_name', models.CharField(max_length=200, verbose_name='Nome do titular do projeto')),
                ('project_class', models.CharField(max_length=100, verbose_name='Classe')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('client_type', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=2, verbose_name='Tipo de cliente')),
                ('cep', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='CEP deve estar no formato XXXXX-XXX', regex='^\\d{5}-?\\d{3}$')], verbose_name='CEP')),
                ('street', models.CharField(max_length=200, verbose_name='Logradouro')),
                ('number', models.CharField(max_length=20, verbose_name='Número')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Bairro')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('complement', models.CharField(blank=True, max_length=200, null=True, verbose_name='Complemento')),
                ('documento', models.CharField(help_text='CPF no formato XXX.XXX.XXX-XX ou CNPJ no formato XX.XXX.XXX/XXXX-XX', max_length=18, verbose_name='Documento')),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Telefone deve estar no formato (XX) XXXXX-XXXX ou (XX) XXXX-XXXX', regex='^\\(\\d{2}\\)\\s?\\d{4,5}-?\\d{4}$')], verbose_name='Telefone do titular')),
                ('latGraus', models.SmallIntegerField(help_text='Parte inteira da latitude (-90 a 90)', verbose_name='Latitude (Graus)')),
                ('latMin', models.SmallIntegerField(help_text='Minutos da latitude (0 a 59)', verbose_name='Latitude (Minutos)')),
                ('latSeg', models.SmallIntegerField(help_text='Segundos da latitude (0 a 59)', verbose_name='Latitude (Segundos)')),
                ('longGraus', models.SmallIntegerField(help_text='Parte inteira da longitude (-180 a 180)', verbose_name='Longitude (Graus)')),
                ('longMin', models.SmallIntegerField(help_text='Minutos da longitude (0 a 59)', verbose_name='Longitude (Minutos)')),
                ('longSeg', models.SmallIntegerField(help_text='Segundos da longitude (0 a 59)', verbose_name='Longitude (Segundos)')),
                ('documentation_complete', models.BooleanField(default=False, verbose_name='Documentação completa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Projeto do Cliente',
                'verbose_name_plural': 'Projetos dos Clientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsumerUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_code_UC', models.CharField(max_length=50, verbose_name='Código do cliente para unidade consumidora')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Porcentagem (%)')),
                ('voltage', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tensão da unidade')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumer_units', to='documents.clientproject')),
            ],
            options={
                'verbose_name': 'Unidade Consumidora',
                'verbose_name_plural': 'Unidades Consumidoras',
            },
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('arquivo', models.FileField(help_text='Arquivo relacionado ao ponto de fiscalização', upload_to=solar.documents.models.get_document_upload_path, verbose_name='Arquivo')),
                ('document_type', models.CharField(choices=[('documento_cliente', 'Documento do Cliente'), ('unidade_geradora_fatura', 'Unidade Geradora (Fatura)'), ('unidades_consumidoras_fatura', 'Unidades Consumidoras (Fatura)'), ('lista_material', 'Lista de Material'), ('procuracao_assinada', 'Procuração Assinada'), ('cartao_cnpj', 'Cartão CNPJ'), ('inscricao_estadual_municipal', 'Inscrição Estadual ou Municipal'), ('contrato_social', 'Contrato Social'), ('outros', 'Outros Documentos')], max_length=50, verbose_name='Tipo do documento')),
                ('file_type', models.CharField(choices=[('photo', 'Foto'), ('pdf', 'PDF'), ('other', 'Outro')], max_length=10, verbose_name='Tipo de arquivo')),
                ('status', models.CharField(choices=[('IN_ANALYSIS', 'Em Análise'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado')], default='IN_ANALYSIS', max_length=20, verbose_name='Status do Documento')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Motivo da rejeição')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.clientproject')),
            ],
            options={
                'verbose_name': 'Documento do Projeto',
                'verbose_name_plural': 'Documentos do Projeto',
            },
        ),
    ]
