# Generated by Django 5.1.7 on 2025-12-17 14:17

import django.core.validators
import django.db.models.deletion
import solar.files.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoCliente', models.CharField(max_length=50, verbose_name='Código único do cliente')),
                ('nomeTitular', models.CharField(max_length=200, verbose_name='Nome do titular do projeto')),
                ('classe', models.CharField(max_length=100, verbose_name='Classe')),
                ('tipoDocumento', models.CharField(choices=[('PJ', 'Pessoa Jurídica'), ('PF', 'Pessoa Física')], default='', max_length=2, verbose_name='Tipo de cliente')),
                ('documento', models.CharField(blank=True, max_length=18, null=True, verbose_name='Documento do Cliente (CPF/CNPJ)')),
                ('voltagem', models.CharField(choices=[('Monofásico - 127V', 'Monofásico - 127V'), ('Monofásico - 220V', 'Monofásico - 220V'), ('Bifásico - 127/220V', 'Bifásico - 127/220V'), ('Bifásico - 220/380V', 'Bifásico - 220/380V'), ('Trifásico - 127/220V', 'Trifásico - 127/220V'), ('Trifásico - 220/380V', 'Trifásico - 220/380V')], help_text='Voltagem do consumidor', max_length=100)),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('telefone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Celular inválido', regex='^\\d{11}$')], verbose_name='Telefone')),
                ('cep', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='CEP deve estar no formato XXXXX-XXX', regex='^\\d{5}-?\\d{3}$')], verbose_name='CEP')),
                ('rua', models.CharField(max_length=200, verbose_name='Logradouro')),
                ('numero', models.CharField(max_length=20, verbose_name='Número')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('complemento', models.CharField(blank=True, max_length=200, null=True, verbose_name='complementoo')),
                ('latGraus', models.SmallIntegerField(help_text='Parte inteira da latitude (-90 a 90)', verbose_name='Latitude (Graus)')),
                ('latMin', models.SmallIntegerField(help_text='Minutos da latitude (0 a 59)', verbose_name='Latitude (Minutos)')),
                ('latSeg', models.SmallIntegerField(help_text='Segundos da latitude (0 a 59)', verbose_name='Latitude (Segundos)')),
                ('longGraus', models.SmallIntegerField(help_text='Parte inteira da longitude (-180 a 180)', verbose_name='Longitude (Graus)')),
                ('longMin', models.SmallIntegerField(help_text='Minutos da longitude (0 a 59)', verbose_name='Longitude (Minutos)')),
                ('longSeg', models.SmallIntegerField(help_text='Segundos da longitude (0 a 59)', verbose_name='Longitude (Segundos)')),
                ('documetacaoCompleta', models.BooleanField(default=False, verbose_name='Documentação completa')),
                ('status', models.CharField(choices=[('Em análise de documentos', 'Analise De Documentos'), ('Projeto em Execução', 'Execucao'), ('Pagamento da TRT/ART e pagamento do projeto', 'Pagamentos'), ('Projeto em análise técnica', 'Analise Tecnica'), ('Projeto aprovado', 'Aprovado'), ('Projeto reprovado', 'Reprovado'), ('Projeto em vistoria', 'Vistoria'), ('Projeto finalizado', 'Concluido')], default='Em análise de documentos', max_length=43, verbose_name='Status do Projeto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Projeto do Cliente',
                'verbose_name_plural': 'Projetos dos Clientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsumerUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoCliente', models.CharField(max_length=50, verbose_name='Código único do cliente')),
                ('porcentagem', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Porcentagem (%)')),
                ('priority_level', models.PositiveSmallIntegerField(blank=True, help_text='Um valor inteiro, onde o número mais baixo indica maior prioridade. Deve ser único por projeto.', null=True, verbose_name='Nível de Prioridade')),
                ('prioridade_is_porcentagem', models.BooleanField(default=True, help_text='Se marcado, a prioridade será determinada pela porcentagem em vez do nível de prioridade.', verbose_name='Prioridade baseada em porcentagem')),
                ('project', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='consumer_units', to='documents.clientproject')),
            ],
            options={
                'verbose_name': 'Unidade Consumidora',
                'verbose_name_plural': 'Unidades Consumidoras',
                'ordering': ['priority_level'],
            },
        ),
        migrations.CreateModel(
            name='ListaDeMateriais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo do Inversor ou Módulo')),
                ('marca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca dos Módulos Fotovoltaicos')),
                ('quantidade', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de módulos')),
                ('modelo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo dos módulos')),
                ('potencia', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Potência nominal em w ou kW')),
                ('unidade_de_medida', models.CharField(choices=[('W', 'Wats'), ('kW', 'KiloWats')], default='wats', help_text='Voltagem do consumidor', max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_lists', to='documents.clientproject')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(help_text='Arquivo do documento. Máximo 10 MB. Formatos: PDF, JPG, PNG, DOC, DOCX, XLS, XLSX', upload_to=solar.files.utils.get_document_upload_path, validators=[solar.files.utils.validate_file_size, solar.files.utils.validate_file_extension], verbose_name='Arquivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('document_name', models.CharField(blank=True, max_length=80, null=True, verbose_name='Nome opcional para o documento')),
                ('document_type', models.CharField(choices=[('documento_cliente', 'Documento do Cliente'), ('unidade_geradora_fatura', 'Unidade Geradora (Fatura)'), ('unidades_consumidoras_fatura', 'Unidades Consumidoras (Fatura)'), ('lista_material', 'Lista de Material'), ('procuracao_assinada', 'Procuração Assinada'), ('pagamento_art', 'Documento que comprove o pagamento da ART'), ('pagamento_trt', 'Documento que comprove o pagamento da TRT'), ('inscricao_municipal', 'Documento que comprove o pagamento da inscrição municipal'), ('inscricao_estadual', 'Documento que comprove o pagamento da inscrição estadual'), ('cartao_cnpj', 'Cartão CNPJ'), ('contrato_social', 'Contrato Social'), ('boleto', 'Boleto'), ('comprovante_de_pagamento', 'Comprovante de Pagamento'), ('outros', 'Outros Documentos')], max_length=80, verbose_name='Tipo do documento')),
                ('status', models.CharField(choices=[('IN_ANALYSIS', 'Em Análise'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado')], default='IN_ANALYSIS', max_length=20, verbose_name='Status do Documento')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Motivo da rejeição')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.clientproject')),
                ('related_payment_document', models.ForeignKey(blank=True, help_text='Documento relacionado (boleto para comprovante ou vice-versa)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_proofs', to='documents.projectdocument')),
            ],
            options={
                'verbose_name': 'Documento do Projeto',
                'verbose_name_plural': 'Documentos do Projeto',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'document_type'], name='documents_p_project_8b54f0_idx'), models.Index(fields=['status'], name='documents_p_status_8afb31_idx')],
            },
        ),
    ]
