# Generated by Django 5.1.7 on 2026-03-04 (Manual Fix)

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        # Removemos as operações RemoveField de 'parcelas', 'tipo_financeiro' e 'valor_financeiro'
        # pois esses campos não constam na migration 0001_initial.py.

        # Ajuste de metadados e textos de ajuda para ConsumerUnit
        migrations.AlterField(
            model_name='consumerunit',
            name='priority_level',
            field=models.PositiveSmallIntegerField(
                blank=True, 
                help_text='Um valor inteiro...', 
                null=True, 
                verbose_name='Nível de Prioridade'
            ),
        ),

        # Ajuste de metadados para ProjectDocument
        migrations.AlterField(
            model_name='projectdocument',
            name='related_payment_document',
            field=models.ForeignKey(
                blank=True, 
                help_text='Boleto relacionado', 
                null=True, 
                on_delete=django.db.models.deletion.CASCADE, 
                related_name='payment_proofs', 
                to='documents.projectdocument'
            ),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='status',
            field=models.CharField(
                choices=[('IN_ANALYSIS', 'Em Análise'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado')], 
                default='IN_ANALYSIS', 
                max_length=20, 
                verbose_name='Status'
            ),
        ),

        # Sincronização da precisão da Potência na ListaDeMateriais (de 7,2 para 20,10)
        migrations.AlterField(
            model_name='listademateriais',
            name='potencia',
            field=models.DecimalField(
                blank=True, 
                decimal_places=10, 
                max_digits=20, 
                null=True, 
                verbose_name='Potência nominal em w ou kW'
            ),
        ),
    ]