# Generated by Django 5.1.7 on 2025-08-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientproject',
            name='status',
            field=models.CharField(choices=[('Projeto em análise', 'Em Analise'), ('Projeto com documentação aprovada', 'Aprovado'), ('Projeto em execução', 'Em Andamento'), ('Projeto finalizado', 'Concluido')], default='Projeto em análise', max_length=40, verbose_name='Status do Projeto'),
        ),
    ]
