# Generated by Django 5.1.7 on 2025-09-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientproject',
            name='valor_financeiro',
            field=models.DecimalField(decimal_places=2, help_text='Valor em reais com 2 casas decimais', max_digits=10, null=True, verbose_name='Valor Financeiro'),
        ),
    ]
