# Generated by Django 5.1.7 on 2026-01-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listademateriais',
            name='potencia_mod_fotovoltaico',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Potência de cada Módulo Fotovoltaico (W)'),
        ),
    ]
