# Generated by Django 5.1.7 on 2025-09-26 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdocument',
            name='file',
        ),
        migrations.RemoveField(
            model_name='projectdocument',
            name='file_type',
        ),
    ]
