# Generated by Django 5.1.7 on 2025-08-08 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientproject',
            name='created_by',
        ),
    ]
