# Generated by Django 5.1.7 on 2025-09-03 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientproject',
            name='documento',
            field=models.CharField(help_text='CPF no formato XXX.XXX.XXX-XX ou CNPJ no formato XX.XXX.XXX/XXXX-XX', max_length=18, verbose_name='Númeor doo CPF ou CNPJ'),
        ),
    ]
