# Generated by Django 5.1.7 on 2026-03-04 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientproject',
            name='parcelas',
        ),
        migrations.RemoveField(
            model_name='clientproject',
            name='tipo_financeiro',
        ),
        migrations.RemoveField(
            model_name='clientproject',
            name='valor_financeiro',
        ),
        migrations.RemoveField(
            model_name='consumerunit',
            name='priodidade_is_porcentagem',
        ),
        migrations.RemoveField(
            model_name='listademateriais',
            name='marca_inversores',
        ),
        migrations.RemoveField(
            model_name='listademateriais',
            name='marca_mod_fotovoltaico',
        ),
        migrations.RemoveField(
            model_name='listademateriais',
            name='modelo_inversores',
        ),
        migrations.RemoveField(
            model_name='listademateriais',
            name='modelo_mod_fotovoltaico',
        ),
        migrations.RemoveField(
            model_name='listademateriais',
            name='potencia_mod_fotovoltaico',
        ),
        migrations.RemoveField(
            model_name='listademateriais',
            name='potencia_nominal_inversores',
        ),
        migrations.RemoveField(
            model_name='listademateriais',
            name='quantd_inversores',
        ),
        migrations.RemoveField(
            model_name='listademateriais',
            name='quantd_mod_fotovoltaico',
        ),
        migrations.AddField(
            model_name='clientproject',
            name='documento',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='Documento do Cliente (CPF/CNPJ)'),
        ),
        migrations.AddField(
            model_name='consumerunit',
            name='prioridade_is_porcentagem',
            field=models.BooleanField(default=True, help_text='Se marcado...', verbose_name='Prioridade baseada em porcentagem'),
        ),
        migrations.AddField(
            model_name='listademateriais',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca dos Módulos Fotovoltaicos'),
        ),
        migrations.AddField(
            model_name='listademateriais',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo dos módulos'),
        ),
        migrations.AddField(
            model_name='listademateriais',
            name='potencia',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True, verbose_name='Potência de cada Módulo Fotovoltaico (W)'),
        ),
        migrations.AddField(
            model_name='listademateriais',
            name='quantidade',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de módulos'),
        ),
        migrations.AddField(
            model_name='listademateriais',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo do Inversor ou Módulo'),
        ),
        migrations.AddField(
            model_name='listademateriais',
            name='unidade_de_medida',
            field=models.CharField(choices=[('W', 'Wats'), ('kW', 'KiloWats')], default='wats', help_text='Unidade de medida', max_length=100),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='document_name',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Nome opcional'),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo da rejeição'),
        ),
        migrations.AlterField(
            model_name='consumerunit',
            name='priority_level',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Um valor inteiro...', null=True, verbose_name='Nível de Prioridade'),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='related_payment_document',
            field=models.ForeignKey(blank=True, help_text='Boleto relacionado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_proofs', to='documents.projectdocument'),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='status',
            field=models.CharField(choices=[('IN_ANALYSIS', 'Em Análise'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado')], default='IN_ANALYSIS', max_length=20, verbose_name='Status'),
        ),
    ]
