# Generated by Django 5.1.7 on 2026-03-04 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientproject',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='consumerunit',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='consumer_units', to='documents.clientproject'),
        ),
        migrations.AddField(
            model_name='listademateriais',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_lists', to='documents.clientproject'),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.clientproject'),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='related_payment_document',
            field=models.ForeignKey(blank=True, help_text='Boleto relacionado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_proofs', to='documents.projectdocument'),
        ),
        migrations.AddIndex(
            model_name='projectdocument',
            index=models.Index(fields=['project', 'document_type'], name='documents_p_project_8b54f0_idx'),
        ),
        migrations.AddIndex(
            model_name='projectdocument',
            index=models.Index(fields=['status'], name='documents_p_status_8afb31_idx'),
        ),
    ]
