# Generated by Django 5.1.7 on 2025-08-11 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_clientproject_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdocument',
            name='approved_by',
        ),
    ]
