# Generated by Django 5.1.7 on 2025-11-23 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_clientproject_id_alter_consumerunit_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listademateriais',
            name='nome',
        ),
        migrations.AddField(
            model_name='listademateriais',
            name='inversor_ou_modulo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Inversor ou Módulo'),
        ),
    ]
