# Generated by Django 5.1.7 on 2025-08-07 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_clientproject_client_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientproject',
            name='client_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id', to=settings.AUTH_USER_MODEL),
        ),
    ]
