# Generated by Django 5.1.7 on 2025-08-13 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_clientproject_client_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumerunit',
            name='client_code_UC',
        ),
    ]
