# Generated by Django 5.1.7 on 2025-09-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_projectdocument_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerunit',
            name='priority_level',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Um valor inteiro, onde o número mais baixo indica maior prioridade. Deve ser único por projeto.', null=True, verbose_name='Nível de Prioridade'),
        ),
    ]
