# Generated by Django 5.1.7 on 2025-11-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_remove_listademateriais_nome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listademateriais',
            name='inversor_ou_modulo',
        ),
        migrations.AddField(
            model_name='listademateriais',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo do Inversor ou Módulo'),
        ),
    ]
