# Generated by Django 5.1.7 on 2025-09-26 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_consumerunit_priority_level'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consumerunit',
            unique_together=set(),
        ),
    ]
