# Generated by Django 5.1.7 on 2025-09-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_clientproject_valor_financeiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientproject',
            name='valor_financeiro',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valor em reais com 2 casas decimais', max_digits=10, verbose_name='Valor Financeiro'),
        ),
    ]
