# Generated by Django 5.1.7 on 2025-11-05 21:03

import solar.documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_consumerunit_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectdocument',
            options={'ordering': ['-created_at'], 'verbose_name': 'Documento do Projeto', 'verbose_name_plural': 'Documentos do Projeto'},
        ),
        migrations.AlterField(
            model_name='clientproject',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='clientproject',
            name='voltagem',
            field=models.CharField(default=220, help_text='Voltagem da unidade geradora', verbose_name='voltagem'),
        ),
        migrations.AlterField(
            model_name='consumerunit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='arquivo',
            field=models.FileField(help_text='Arquivo do documento. Máximo 10 MB. Formatos: PDF, JPG, PNG, DOC, DOCX, XLS, XLSX', upload_to=solar.documents.models.get_document_upload_path, validators=[solar.documents.models.validate_file_size, solar.documents.models.validate_file_extension], verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='projectdocument',
            index=models.Index(fields=['project', 'document_type'], name='documents_p_project_8b54f0_idx'),
        ),
        migrations.AddIndex(
            model_name='projectdocument',
            index=models.Index(fields=['status'], name='documents_p_status_8afb31_idx'),
        ),
    ]
