# Generated by Django 5.1.7 on 2025-11-25 21:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_remove_listademateriais_inversor_ou_modulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientproject',
            name='boleto',
            field=models.ImageField(blank=True, help_text='Upload do boleto de pagamento (imagem ou PDF convertido)', null=True, upload_to='projects/boletos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'], message='Apenas arquivos JPG, JPEG, PNG ou PDF são permitidos.')], verbose_name='Boleto'),
        ),
        migrations.AddField(
            model_name='clientproject',
            name='boleto_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação do Boleto'),
        ),
        migrations.AddField(
            model_name='clientproject',
            name='boleto_status',
            field=models.CharField(choices=[('IN_ANALYSIS', 'Em Análise'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado')], default='IN_ANALYSIS', help_text='Status da análise do boleto', max_length=20, verbose_name='Status do Boleto'),
        ),
        migrations.AddField(
            model_name='clientproject',
            name='boleto_uploaded_at',
            field=models.DateTimeField(blank=True, help_text='Data/hora em que o boleto foi enviado', null=True, verbose_name='Data de Upload do Boleto'),
        ),
        migrations.AddField(
            model_name='clientproject',
            name='comprovante_pagamento',
            field=models.ImageField(blank=True, help_text='Upload do comprovante de pagamento relacionado ao boleto', null=True, upload_to='projects/comprovantes/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'], message='Apenas arquivos JPG, JPEG, PNG ou PDF são permitidos.')], verbose_name='Comprovante de Pagamento'),
        ),
        migrations.AddField(
            model_name='clientproject',
            name='comprovante_pagamento_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação do Comprovante'),
        ),
        migrations.AddField(
            model_name='clientproject',
            name='comprovante_pagamento_status',
            field=models.CharField(choices=[('IN_ANALYSIS', 'Em Análise'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado')], default='IN_ANALYSIS', help_text='Status da análise do comprovante de pagamento', max_length=20, verbose_name='Status do Comprovante'),
        ),
        migrations.AddField(
            model_name='clientproject',
            name='comprovante_pagamento_uploaded_at',
            field=models.DateTimeField(blank=True, help_text='Data/hora em que o comprovante foi enviado', null=True, verbose_name='Data de Upload do Comprovante'),
        ),
        migrations.AddField(
            model_name='clientproject',
            name='payment_rejection_reason',
            field=models.TextField(blank=True, help_text='Motivo da rejeição do boleto ou comprovante (se aplicável)', null=True, verbose_name='Motivo da Rejeição'),
        ),
    ]
