# Generated by Django 5.1.7 on 2025-09-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_clientproject_valor_financeiro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientproject',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='clientproject',
            name='email',
        ),
        migrations.RemoveField(
            model_name='clientproject',
            name='celular',
        ),
        migrations.AlterField(
            model_name='clientproject',
            name='tipoDocumento',
            field=models.CharField(choices=[('PJ', 'Pessoa Jurídica')], default='PJ', max_length=2, verbose_name='Tipo de cliente'),
        ),
    ]
