# Generated by Django 5.1.7 on 2025-09-16 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_remove_clientproject_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerunit',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumer_units', to='documents.clientproject'),
        ),
    ]
