# Generated by Django 5.1.7 on 2025-11-07 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_projectdocument_options_alter_clientproject_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdocument',
            name='rejection_reason',
        ),
    ]
