# Generated by Django 5.1.7 on 2025-11-25 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_clientproject_boleto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientproject',
            name='boleto',
        ),
        migrations.RemoveField(
            model_name='clientproject',
            name='boleto_approved_at',
        ),
        migrations.RemoveField(
            model_name='clientproject',
            name='boleto_status',
        ),
        migrations.RemoveField(
            model_name='clientproject',
            name='boleto_uploaded_at',
        ),
        migrations.RemoveField(
            model_name='clientproject',
            name='comprovante_pagamento',
        ),
        migrations.RemoveField(
            model_name='clientproject',
            name='comprovante_pagamento_approved_at',
        ),
        migrations.RemoveField(
            model_name='clientproject',
            name='comprovante_pagamento_status',
        ),
        migrations.RemoveField(
            model_name='clientproject',
            name='comprovante_pagamento_uploaded_at',
        ),
        migrations.RemoveField(
            model_name='clientproject',
            name='parcelas',
        ),
        migrations.RemoveField(
            model_name='clientproject',
            name='payment_rejection_reason',
        ),
        migrations.RemoveField(
            model_name='clientproject',
            name='tipo_financeiro',
        ),
        migrations.RemoveField(
            model_name='clientproject',
            name='valor_financeiro',
        ),
    ]
