# Generated by Django 5.1.7 on 2025-11-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_remove_clientproject_boleto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdocument',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo da rejeição'),
        ),
    ]
