# Generated by Django 5.1.7 on 2025-11-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_remove_projectdocument_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientproject',
            name='voltagem',
            field=models.CharField(choices=[('127', 'Monofásico - 127V'), ('220', 'Monofásico - 220V'), ('127/220', 'Bifásico - 127/220V'), ('220/380', 'Bifásico - 220/380V'), ('127/220T', 'Trifásico - 127/220V'), ('220/380T', 'Trifásico - 220/380V')], help_text='Voltagem do consumidor', max_length=100),
        ),
    ]
