# Generated by Django 5.1.7 on 2025-09-16 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_alter_consumerunit_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerunit',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='consumer_units', to='documents.clientproject'),
        ),
    ]
