# Generated by Django 5.1.7 on 2025-11-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_alter_clientproject_voltagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientproject',
            name='voltagem',
            field=models.CharField(choices=[('Monofásico - 127V', 'Monofásico - 127V'), ('Monofásico - 220V', 'Monofásico - 220V'), ('Bifásico - 127/220V', 'Bifásico - 127/220V'), ('Bifásico - 220/380V', 'Bifásico - 220/380V'), ('Trifásico - 127/220V', 'Trifásico - 127/220V'), ('Trifásico - 220/380V', 'Trifásico - 220/380V')], help_text='Voltagem do consumidor', max_length=100),
        ),
    ]
