# Generated by Django 5.1.7 on 2026-10-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_adjust_payment_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientproject',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='clientproject',
            name='status',
            field=models.CharField(choices=[('Em análise de documentos', 'Analise De Documentos'), ('Projeto em Execução', 'Execucao'), ('Pagamento da TRT/ART', 'Pagamento Trt Art'), ('Projeto em análise técnica', 'Analise Tecnica'), ('Projeto aprovado', 'Aprovado'), ('Projeto reprovado', 'Reprovado'), ('Projeto em vistoria', 'Vistoria'), ('Projeto finalizado', 'Concluido')], default='Em análise de documentos', max_length=43, verbose_name='Status do Projeto'),
        ),
        migrations.AlterField(
            model_name='consumerunit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='listademateriais',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='document_type',
            field=models.CharField(choices=[('documento_cliente', 'Documento do Cliente'), ('unidade_geradora_fatura', 'Unidade Geradora (Fatura)'), ('unidades_consumidoras_fatura', 'Unidades Consumidoras (Fatura)'), ('lista_material', 'Lista de Material'), ('procuracao_assinada', 'Procuração Assinada'), ('pagamento_art', 'Documento que comprove o pagamento da ART'), ('pagamento_trt', 'Documento que comprove o pagamento da TRT'), ('inscricao_municipal', 'Documento que comprove o pagamento da inscrição municipal'), ('inscricao_estadual', 'Documento que comprove o pagamento da inscrição estadual'), ('cartao_cnpj', 'Cartão CNPJ'), ('contrato_social', 'Contrato Social'), ('boleto', 'Boleto'), ('comprovante_de_pagamento', 'Comprovante de Pagamento'), ('formulario', 'Formulário'), ('diagrama_unifilar', 'Diagrama Unifilar'), ('dados_geradora', 'Dados da Geradora'), ('unidades_consumidoras_extra', 'Unidades Consumidoras (Opcional)'), ('memorial', 'Memorial'), ('art_documento', 'ART'), ('documento_de_posse', 'Documento de Posse'), ('outros', 'Outros Documentos')], max_length=80, verbose_name='Tipo do documento'),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectprotocol',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectstatushistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='projectdocument',
            index=models.Index(fields=['project', 'document_type'], name='documents_p_project_8b54f0_idx'),
        ),
        migrations.AddIndex(
            model_name='projectdocument',
            index=models.Index(fields=['status'], name='documents_p_status_8afb31_idx'),
        ),
    ]
