# Generated by Django 5.1.7 on 2026-10-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_alter_clientproject_id_alter_clientproject_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientproject',
            name='grupo',
            field=models.CharField(blank=True, choices=[('ENERGISA', 'Energisa'), ('COELBA', 'Coelba')], max_length=20, null=True, verbose_name='Grupo (Concessionária)'),
        ),
    ]
