# Generated by Django 5.1.7 on 2025-11-30 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_projectdocument_document_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerunit',
            name='unidade_de_medida',
            field=models.CharField(choices=[('w', 'Wats'), ('kw', 'KiloWats')], default='wats', help_text='Voltagem do consumidor', max_length=100),
        ),
    ]
