# Generated by Django 5.1.7 on 2026-10-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_clientproject_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientproject',
            name='grupo',
            field=models.CharField(blank=True, choices=[('energisa', 'Energisa'), ('coelba', 'Coelba')], max_length=20, null=True, verbose_name='Grupo (Concessionária)'),
        ),
    ]
