# Generated by Django 5.1.7 on 2025-11-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_consumerunit_unidade_de_medida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumerunit',
            name='unidade_de_medida',
        ),
        migrations.AddField(
            model_name='listademateriais',
            name='unidade_de_medida',
            field=models.CharField(choices=[('w', 'Wats'), ('kw', 'KiloWats')], default='wats', help_text='Voltagem do consumidor', max_length=100),
        ),
        migrations.AlterField(
            model_name='listademateriais',
            name='potencia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Potência nominal em w ou kW'),
        ),
    ]
