# Generated by Django 5.1.7 on 2026-10-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_alter_clientproject_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientproject',
            name='latGraus',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Latitude em formato decimal ou graus (-90 a 90)', max_digits=10, null=True, verbose_name='Latitude (Graus/Decimal)'),
        ),
        migrations.AlterField(
            model_name='clientproject',
            name='latMin',
            field=models.SmallIntegerField(blank=True, default=0, help_text='Minutos da latitude (0 a 59)', null=True, verbose_name='Latitude (Minutos)'),
        ),
        migrations.AlterField(
            model_name='clientproject',
            name='latSeg',
            field=models.SmallIntegerField(blank=True, default=0, help_text='Segundos da latitude (0 a 59)', null=True, verbose_name='Latitude (Segundos)'),
        ),
        migrations.AlterField(
            model_name='clientproject',
            name='longGraus',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Longitude em formato decimal ou graus (-180 a 180)', max_digits=11, null=True, verbose_name='Longitude (Graus/Decimal)'),
        ),
        migrations.AlterField(
            model_name='clientproject',
            name='longMin',
            field=models.SmallIntegerField(blank=True, default=0, help_text='Minutos da longitude (0 a 59)', null=True, verbose_name='Longitude (Minutos)'),
        ),
        migrations.AlterField(
            model_name='clientproject',
            name='longSeg',
            field=models.SmallIntegerField(blank=True, default=0, help_text='Segundos da longitude (0 a 59)', null=True, verbose_name='Longitude (Segundos)'),
        ),
    ]
