# Generated by Django 5.1.7 on 2026-10-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_alter_clientproject_latgraus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listademateriais',
            name='disjuntor',
            field=models.FloatField(blank=True, null=True, verbose_name='Disjuntor (A)'),
        ),
        migrations.AddField(
            model_name='listademateriais',
            name='tensao_nominal',
            field=models.FloatField(blank=True, null=True, verbose_name='Tensão Nominal (V)'),
        ),
    ]
