# Generated by Django 5.1.7 on 2026-01-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_clientproject_id_alter_consumerunit_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listademateriais',
            name='potencia',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True, verbose_name='Potência de cada Módulo Fotovoltaico (W)'),
        ),
    ]