# Generated by Django 5.1.7 on 2026-10-09 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_4e3567_idx',
            old_name='notif_recipient_is_read_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_project_2e98ed_idx',
            old_name='notif_project_idx',
        ),
    ]
