# Generated by Django 5.1.7 on 2025-05-06 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_emaillog'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da alteração')),
                ('field_name', models.CharField(max_length=100, verbose_name='Campo alterado')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='Valor antigo')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='Valor novo')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes_made', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuário alterado')),
            ],
            options={
                'verbose_name': 'Log de Alteração de Usuário',
                'verbose_name_plural': 'Logs de Alterações de Usuários',
                'ordering': ['-changed_at'],
            },
        ),
    ]
