# Generated by Django 5.1.7 on 2025-06-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userexport_delete_historicaluser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='acesso_especial_cpf',
            field=models.BooleanField(default=False, help_text='Usuário pode fazer login via link especial usando apenas CPF', verbose_name='Acesso Especial via CPF'),
        ),
        migrations.AddField(
            model_name='user',
            name='primeiro_acesso_especial',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Primeiro Acesso Especial'),
        ),
    ]
