# Generated by Django 5.1.7 on 2025-11-17 18:15

import django.db.models.deletion
import solar.files.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(help_text='Arquivo do documento. Máximo 10 MB. Formatos: PDF, JPG, PNG, DOC, DOCX, XLS, XLSX', upload_to=solar.files.utils.get_document_upload_path, validators=[solar.files.utils.validate_file_size, solar.files.utils.validate_file_extension], verbose_name='Arquivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('document_type', models.CharField(choices=[('documento_cliente', 'Documento do Cliente'), ('unidade_geradora_fatura', 'Unidade Geradora (Fatura)'), ('unidades_consumidoras_fatura', 'Unidades Consumidoras (Fatura)'), ('lista_material', 'Lista de Material'), ('procuracao_assinada', 'Procuração Assinada'), ('pagamento_art', 'Documento que comprove o pagamento da ART'), ('pagamento_trt', 'Documento que comprove o pagamento da TRT'), ('inscricao_municipal', 'Documento que comprove o pagamento da inscrição municipal'), ('inscricao_estadual', 'Documento que comprove o pagamento da inscrição estadual'), ('cartao_cnpj', 'Cartão CNPJ'), ('contrato_social', 'Contrato Social'), ('boleto', 'Boleto'), ('comprovante_de_pagamento', 'Comprovante de Pagamento'), ('outros', 'Outros Documentos')], max_length=80, verbose_name='Tipo do documento')),
                ('status', models.CharField(choices=[('IN_ANALYSIS', 'Em Análise'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado')], default='IN_ANALYSIS', max_length=20, verbose_name='Status do Documento')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento do Usuário',
                'verbose_name_plural': 'Documentos dos Usuários',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['user', 'document_type'], name='files_docum_user_id_f65b95_idx'), models.Index(fields=['status'], name='files_docum_status_64f55a_idx')],
            },
        ),
    ]