# Generated by Django 5.1.7 on 2026-03-04 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='documentuser',
            index=models.Index(fields=['user', 'document_type'], name='files_docum_user_id_f65b95_idx'),
        ),
        migrations.AddIndex(
            model_name='documentuser',
            index=models.Index(fields=['status'], name='files_docum_status_64f55a_idx'),
        ),
    ]
