# Generated by Django 5.1.7 on 2025-11-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_documentuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentuser',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo da rejeição'),
        ),
    ]
