# Generated by Django 5.1.7 on 2025-11-26 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_documentuser_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentuser',
            name='related_payment_document',
            field=models.ForeignKey(blank=True, help_text='Documento relacionado (boleto para comprovante ou vice-versa)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_proofs', to='files.documentuser'),
        ),
    ]
