# Generated by Django 5.1.7 on 2025-11-30 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_documentuser_related_payment_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentuser',
            name='document_name',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Nome opcional para o documento'),
        ),
    ]
