# Generated by Django 5.1.7 on 2025-05-16 12:06

import arcanosig.sac.models
import django.core.validators
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRelatorioInteligencia',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('numero', models.PositiveIntegerField(help_text='Número sequencial do relatório (apenas dígitos)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número Sequencial')),
                ('numero_ano', models.CharField(db_index=True, editable=False, max_length=20, verbose_name='Identificação Completa')),
                ('tipo', models.CharField(choices=[('PRELIMINAR', 'Preliminar'), ('FINAL', 'Final')], default='PRELIMINAR', help_text='Determina se o relatório é final ou preliminar', max_length=15, verbose_name='Tipo do relatório')),
                ('arquivo_pdf', models.TextField(help_text='Documento PDF do relatório de inteligência', max_length=100, validators=[django.core.validators.FileExtensionValidator(['pdf']), arcanosig.sac.models.validar_tamanho_pdf], verbose_name='Arquivo PDF')),
                ('criado_em', models.DateTimeField(blank=True, editable=False, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False, verbose_name='Atualizado em')),
                ('quantidade_acessos', models.PositiveIntegerField(default=0, verbose_name='Número de Acessos')),
                ('ultima_visualizacao', models.DateTimeField(blank=True, null=True, verbose_name='Última Visualização')),
                ('qtd_homicidio', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Homicídio')),
                ('qtd_tentativa_homicidio', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tentativa de Homicídio')),
                ('qtd_latrocinio', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Latrocínio')),
                ('qtd_tentativa_latrocinio', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tentativa de Latrocínio')),
                ('qtd_feminicidio', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Feminicídio')),
                ('qtd_tentativa_feminicidio', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tentativa de Feminicídio')),
                ('qtd_morte_intervencao', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Morte Decorrente de Intervenção')),
                ('qtd_mandado_prisao', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cumprimento de Mandado de Prisão')),
                ('qtd_encontro_cadaver', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Encontro de Cadáver')),
                ('qtd_apreensao_drogas', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Apreensão de Drogas')),
                ('qtd_apreensao_armas', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Apreensão de Armas')),
                ('qtd_ocorrencia_repercussao', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ocorrências de Repercussão')),
                ('qtd_outras_intercorrencias', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Outras Intercorrências')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('analista', models.ForeignKey(blank=True, db_constraint=False, help_text='Usuário responsável por produzir o relatório', limit_choices_to={'is_sac': True, 'sac_profile': 'ANALISTA'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Analista')),
                ('focal', models.ForeignKey(blank=True, db_constraint=False, help_text='Usuário responsável por adicionar o relatório', limit_choices_to={'is_sac': True, 'sac_profile': 'FOCAL'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Focal')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Relatório de Inteligência',
                'verbose_name_plural': 'historical Relatórios de Inteligência',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='RelatorioInteligencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.PositiveIntegerField(help_text='Número sequencial do relatório (apenas dígitos)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número Sequencial')),
                ('numero_ano', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Identificação Completa')),
                ('tipo', models.CharField(choices=[('PRELIMINAR', 'Preliminar'), ('FINAL', 'Final')], default='PRELIMINAR', help_text='Determina se o relatório é final ou preliminar', max_length=15, verbose_name='Tipo do relatório')),
                ('arquivo_pdf', models.FileField(help_text='Documento PDF do relatório de inteligência', upload_to=arcanosig.sac.models.caminho_relatorio_inteligencia, validators=[django.core.validators.FileExtensionValidator(['pdf']), arcanosig.sac.models.validar_tamanho_pdf], verbose_name='Arquivo PDF')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('quantidade_acessos', models.PositiveIntegerField(default=0, verbose_name='Número de Acessos')),
                ('ultima_visualizacao', models.DateTimeField(blank=True, null=True, verbose_name='Última Visualização')),
                ('qtd_homicidio', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Homicídio')),
                ('qtd_tentativa_homicidio', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tentativa de Homicídio')),
                ('qtd_latrocinio', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Latrocínio')),
                ('qtd_tentativa_latrocinio', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tentativa de Latrocínio')),
                ('qtd_feminicidio', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Feminicídio')),
                ('qtd_tentativa_feminicidio', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tentativa de Feminicídio')),
                ('qtd_morte_intervencao', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Morte Decorrente de Intervenção')),
                ('qtd_mandado_prisao', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cumprimento de Mandado de Prisão')),
                ('qtd_encontro_cadaver', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Encontro de Cadáver')),
                ('qtd_apreensao_drogas', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Apreensão de Drogas')),
                ('qtd_apreensao_armas', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Apreensão de Armas')),
                ('qtd_ocorrencia_repercussao', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ocorrências de Repercussão')),
                ('qtd_outras_intercorrencias', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Outras Intercorrências')),
                ('analista', models.ForeignKey(help_text='Usuário responsável por produzir o relatório', limit_choices_to={'is_sac': True, 'sac_profile': 'ANALISTA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatorios_criados', to=settings.AUTH_USER_MODEL, verbose_name='Analista')),
                ('focal', models.ForeignKey(help_text='Usuário responsável por adicionar o relatório', limit_choices_to={'is_sac': True, 'sac_profile': 'FOCAL'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatorios_focais', to=settings.AUTH_USER_MODEL, verbose_name='Focal')),
            ],
            options={
                'verbose_name': 'Relatório de Inteligência',
                'verbose_name_plural': 'Relatórios de Inteligência',
                'ordering': ['-criado_em'],
                'permissions': [('view_confidential_report', 'Pode visualizar relatórios confidenciais'), ('add_intelligence_report', 'Pode adicionar relatórios de inteligência')],
            },
        ),
        migrations.CreateModel(
            name='RelatorioInteligenciaChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da alteração')),
                ('change_type', models.CharField(choices=[('create', 'Criação'), ('update', 'Atualização'), ('delete', 'Exclusão')], max_length=10, verbose_name='Tipo de Alteração')),
                ('field_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo alterado')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='Valor antigo')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='Valor novo')),
                ('deleted_report_id', models.UUIDField(blank=True, null=True, verbose_name='ID do Relatório Deletado')),
                ('duracao_visualizacao', models.DurationField(blank=True, null=True, verbose_name='Duração da Visualização')),
                ('dispositivo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dispositivo')),
                ('navegador', models.CharField(blank=True, max_length=100, null=True, verbose_name='Navegador')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_changes_made', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('relatorio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='sac.relatoriointeligencia', verbose_name='Relatório Alterado')),
            ],
            options={
                'verbose_name': 'Log de Alteração de Relatório',
                'verbose_name_plural': 'Logs de Alterações de Relatórios',
                'ordering': ['-changed_at'],
            },
        ),
    ]
