# Generated by Django 5.1.7 on 2025-06-02 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sac', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='relatoriointeligenciachangelog',
            name='endereco_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP'),
        ),
        migrations.AddField(
            model_name='relatoriointeligenciachangelog',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_access_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que acessou'),
        ),
        migrations.AlterField(
            model_name='relatoriointeligenciachangelog',
            name='change_type',
            field=models.CharField(choices=[('create', 'Criação'), ('update', 'Atualização'), ('delete', 'Exclusão'), ('access', 'Acesso'), ('download', 'Download'), ('view_pdf', 'Visualização PDF')], max_length=20, verbose_name='Tipo de Alteração'),
        ),
        migrations.AlterField(
            model_name='relatoriointeligenciachangelog',
            name='dispositivo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dispositivo'),
        ),
        migrations.AlterField(
            model_name='relatoriointeligenciachangelog',
            name='navegador',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Navegador'),
        ),
    ]
