# Generated by Django 5.1.7 on 2025-06-02 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sac', '0002_relatoriointeligenciachangelog_endereco_ip_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioCompartilhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cpf', 'Compartilhamento via CPF'), ('especial', 'Link Especial Temporário')], max_length=10)),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('numero_especial', models.CharField(blank=True, max_length=20, null=True)),
                ('senha_especial', models.CharField(blank=True, max_length=20, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('acessos', models.PositiveIntegerField(default=0)),
                ('ultimo_acesso', models.DateTimeField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartilhamentos_criados', to=settings.AUTH_USER_MODEL)),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartilhamentos', to='sac.relatoriointeligencia')),
            ],
            options={
                'verbose_name': 'Compartilhamento de Relatório',
                'verbose_name_plural': 'Compartilhamentos de Relatórios',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='CompartilhamentoAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('sucesso', models.BooleanField(default=False)),
                ('erro', models.TextField(blank=True, null=True)),
                ('acessado_em', models.DateTimeField(auto_now_add=True)),
                ('compartilhamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_acesso', to='sac.relatoriocompartilhamento')),
            ],
            options={
                'ordering': ['-acessado_em'],
            },
        ),
    ]
