@baseUrl = http://localhost:8080
@contentType = application/json

# ==================================================================
# VARIÁVEIS DINÂMICAS
# ==================================================================
@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1OTI4MTYyLCJpYXQiOjE3NDU5MjYzNjIsImp0aSI6IjIwY2UyZTFhMDFhYzRmMzA4MDdiZjQwZjQ3ZWNhYjY1IiwidXNlcl9pZCI6ImEzNGMwMGY5LWVhOTEtNDk0Zi1iZjJkLWM1YWUyYjgxNjllZiJ9.P67WjfG0a4y7Z4x49Vkrjxq-dMFQXgRJmCuZM9c00RE

# ==================================================================
# 1. AUTENTICAÇÃO
# ==================================================================

### Login como Administrador
# @name loginAdmin
POST {{baseUrl}}/auth/jwt/create/
Content-Type: {{contentType}}

{
  "email": "admin@arcanosig.com",
  "password": "Teste123@"
}

# ==================================================================
# 2. LISTAR MEMBROS DA GUARNIÇÃO
# ==================================================================

### Listar membros da guarnição com ID 1
# @name listarMembros
GET {{baseUrl}}/api/v1/oper/guarnicoes/1/membros/
Authorization: Bearer {{adminToken}}
Content-Type: {{contentType}}

# ==================================================================
# 3. ADICIONAR MEMBRO À GUARNIÇÃO
# ==================================================================

### Adicionar um novo membro à guarnição
# @name adicionarMembro
POST {{baseUrl}}/api/v1/oper/guarnicao-membros/
Authorization: Bearer {{adminToken}}
Content-Type: {{contentType}}

{
    "guarnicao_id": 3,
    "user_id": "d2dca9a2-41b0-44da-949a-1d636e0a538c"
}

# ==================================================================
# 4. REMOVER MEMBRO DA GUARNIÇÃO
# ==================================================================

### Remover membro específico da guarnição (substitua {id_membro} pelo ID retornado na listagem)
# @name removerMembro
DELETE {{baseUrl}}/api/v1/oper/guarnicao-membros/{1}/
Authorization: Bearer {{adminToken}}
