# Generated by Django 5.1.7 on 2025-04-03 12:53

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=255, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='O CPF deve conter apenas 11 dígitos numéricos, sem pontos ou traços', regex='^\\d{11}$')], verbose_name='CPF')),
                ('celular', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='O celular deve conter 11 dígitos (DDD + número), sem caracteres especiais', regex='^\\d{11}$')], verbose_name='Celular')),
                ('is_pm', models.BooleanField(default=False, verbose_name='É Policial Militar')),
                ('patent', models.CharField(choices=[('SOLDADO', 'Soldado'), ('CABO', 'Cabo'), ('SARGENTO', 'Sargento'), ('SUBTENENTE', 'Subtenente'), ('TENENTE', 'Tenente'), ('CAPITAO', 'Capitão'), ('MAJOR', 'Major'), ('TENENTE_CORONEL', 'Tenente Coronel'), ('CORONEL', 'Coronel'), ('NAO_APLICAVEL', 'Não Aplicável')], default='NAO_APLICAVEL', max_length=20, verbose_name='Patente')),
                ('matricula', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='Matrícula')),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('access_cpi', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['-created_at'],
            },
        ),
    ]
