# Generated by Django 5.1.7 on 2025-11-23 04:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='cnpj')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF')),
                ('celular', models.CharField(max_length=11, verbose_name='Celular')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_admin', models.BooleanField(default=False, verbose_name='É Administrador')),
                ('is_tecnico', models.BooleanField(default=False, verbose_name='É Técnico')),
                ('is_cliente', models.BooleanField(default=False, verbose_name='É Cliente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_pessoa_juridica', models.BooleanField(default=False, verbose_name='É Pessoa Jurídica')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
            ],
            options={
                'verbose_name': 'Técnico',
                'verbose_name_plural': 'Técnicos',
                'permissions': [('can_view_financial_data', 'Pode visualizar dados financeiros'), ('cannot_edit_financial_data', 'Não pode editar dados financeiros')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('welcome', 'Boas-vindas'), ('password_reset', 'Redefinição de Senha'), ('notification', 'Notificação')], max_length=20)),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('sent', 'Enviado'), ('failed', 'Falhou'), ('pending', 'Pendente')], default='pending', max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de E-mail',
                'verbose_name_plural': 'Logs de E-mails',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='UserChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da alteração')),
                ('field_name', models.CharField(max_length=100, verbose_name='Campo alterado')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='Valor antigo')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='Valor novo')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes_made', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuário alterado')),
            ],
            options={
                'verbose_name': 'Log de Alteração de Usuário',
                'verbose_name_plural': 'Logs de Alterações de Usuários',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'permissions': [('can_view_own_projects', 'Pode visualizar apenas seus próprios projetos'), ('cannot_edit_financial_data', 'Não pode editar dados financeiros')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.tecnico',),
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'permissions': [('can_view_own_projects', 'Pode visualizar apenas seus próprios projetos'), ('cannot_edit_financial_data', 'Não pode editar dados financeiros')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.cliente',),
        ),
    ]
