# Generated by Django 5.1.7 on 2025-11-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_cliente',
            field=models.BooleanField(default=True, verbose_name='É Cliente'),
        ),
    ]
