# Generated by Django 5.1.7 on 2025-09-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_cliente',
            field=models.BooleanField(default=False, verbose_name='É Cliente'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_tecnico',
            field=models.BooleanField(default=False, verbose_name='É Técnico'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='É Administrador'),
        ),
    ]
