# Generated by Django 5.1.7 on 2025-09-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_cliente_user_is_tecnico_alter_user_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_cliente',
            field=models.BooleanField(default=True, verbose_name='É Cliente'),
        ),
    ]
