# Generated by Django 5.1.7 on 2025-10-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_cliente',
            field=models.BooleanField(default=False, verbose_name='É Cliente'),
        ),
    ]
