# Generated by Django 5.1.7 on 2025-11-17 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_is_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserImport',
        ),
        migrations.DeleteModel(
            name='UserExport',
        ),
    ]
