# Generated by Django 5.1.7 on 2025-11-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_userimport_delete_userexport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'permissions': [('can_view_own_projects', 'Pode visualizar apenas seus próprios projetos'), ('cannot_edit_financial_data', 'Não pode editar dados financeiros')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.cliente',),
        ),
        migrations.AddField(
            model_name='user',
            name='is_pessoa_juridica',
            field=models.BooleanField(default=False, verbose_name='É Pessoa Jurídica'),
        ),
        migrations.AlterField(
            model_name='user',
            name='celular',
            field=models.CharField(max_length=11, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='cnpj'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
    ]
