# Generated by Django 5.1.7 on 2025-05-07 14:37

import solar.users.models
import django.core.validators
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userchangelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('email', models.EmailField(db_index=True, max_length=255, verbose_name='Email')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('cpf', models.CharField(db_index=True, max_length=11, validators=[django.core.validators.RegexValidator(message='CPF inválido', regex='^\\d{11}$')], verbose_name='CPF')),
                ('celular', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Celular inválido', regex='^\\d{11}$')], verbose_name='Celular')),
                ('photo', models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png']), solar.users.models.validate_image_size], verbose_name='Foto')),
                ('patent', models.CharField(choices=[('SOLDADO', 'Soldado'), ('CABO', 'Cabo'), ('SARGENTO', 'Sargento'), ('SUBTENENTE', 'Subtenente'), ('TENENTE', 'Tenente'), ('CAPITAO', 'Capitão'), ('MAJOR', 'Major'), ('TENENTE_CORONEL', 'Tenente Coronel'), ('CORONEL', 'Coronel')], default='SOLDADO', max_length=20, verbose_name='Patente')),
                ('is_active', models.BooleanField(default=False, verbose_name='Ativo')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Administrador')),
                ('is_operacoes', models.BooleanField(default=False, verbose_name='Operações')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Atualizado em')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Usuário',
                'verbose_name_plural': 'historical Usuários',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
