# Generated by Django 5.1.7 on 2025-05-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_emaillog_id_alter_userchangelog_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='is_sac',
            field=models.BooleanField(default=False, verbose_name='É SAC'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='sac_profile',
            field=models.CharField(blank=True, choices=[('SEM_ACESSO', 'Sem Acesso'), ('ANALISTA', 'Analista'), ('FOCAL', 'Focal')], max_length=10, null=True, verbose_name='Perfil SAC'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_sac',
            field=models.BooleanField(default=False, verbose_name='É SAC'),
        ),
        migrations.AddField(
            model_name='user',
            name='sac_profile',
            field=models.CharField(blank=True, choices=[('SEM_ACESSO', 'Sem Acesso'), ('ANALISTA', 'Analista'), ('FOCAL', 'Focal')], max_length=10, null=True, verbose_name='Perfil SAC'),
        ),
    ]
