# Generated by Django 5.1.7 on 2025-09-03 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnico',
            fields=[
            ],
            options={
                'verbose_name': 'Técnico',
                'verbose_name_plural': 'Técnicos',
                'permissions': [('can_view_financial_data', 'Pode visualizar dados financeiros'), ('cannot_edit_financial_data', 'Não pode editar dados financeiros')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'permissions': [('can_view_own_projects', 'Pode visualizar apenas seus próprios projetos'), ('cannot_edit_financial_data', 'Não pode editar dados financeiros')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.tecnico',),
        ),
    ]
