# Generated by Django 5.1.7 on 2025-09-09 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_tecnico_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_tecnico',
            field=models.BooleanField(default=True, verbose_name='É Técnico'),
        ),
    ]
