# Generated by Django 5.1.7 on 2025-09-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_is_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_cliente',
            field=models.BooleanField(default=True, verbose_name='É Cliente'),
        ),
    ]
